# Generated by Django 5.2.8 on 2025-11-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('neumorphism', 'Neumorphism'), ('industrial', 'Industrial'), ('isometric', 'Isometric'), ('glassmorphism', 'Glassmorphism'), ('blueprint', 'Blueprint')], default='neumorphism', max_length=20),
        ),
    ]
