# Generated by Django 5.2.8 on 2025-11-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('sp_entity_id', models.CharField(blank=True, help_text='Unique identifier for NetVault SP (e.g., https://netvault.example.com/saml/metadata/)', max_length=255)),
                ('idp_entity_id', models.CharField(blank=True, help_text='Entity ID of the Identity Provider', max_length=255)),
                ('idp_sso_url', models.URLField(blank=True, help_text='IdP Single Sign-On URL', max_length=500)),
                ('idp_slo_url', models.URLField(blank=True, help_text='IdP Single Logout URL (optional)', max_length=500)),
                ('idp_x509_cert', models.TextField(blank=True, help_text='IdP X.509 certificate (PEM format)')),
                ('attr_username', models.CharField(default='http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name', help_text='SAML attribute for username', max_length=100)),
                ('attr_email', models.CharField(default='http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress', help_text='SAML attribute for email', max_length=100)),
                ('attr_first_name', models.CharField(blank=True, default='http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname', help_text='SAML attribute for first name', max_length=100)),
                ('attr_last_name', models.CharField(blank=True, default='http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname', help_text='SAML attribute for last name', max_length=100)),
                ('auto_create_users', models.BooleanField(default=True, help_text='Automatically create users on first SAML login')),
                ('default_role', models.CharField(choices=[('administrator', 'Administrator'), ('operator', 'Operator'), ('viewer', 'Viewer'), ('auditor', 'Auditor')], default='viewer', help_text='Default role for auto-created users', max_length=20)),
                ('want_assertions_signed', models.BooleanField(default=True)),
                ('want_messages_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAML Settings',
                'verbose_name_plural': 'SAML Settings',
                'db_table': 'saml_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_saml_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='saml_name_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
