# Generated by Django 5.2.8 on 2025-11-15 07:53

from django.db import migrations, models


def mark_predefined_device_types(apps, schema_editor):
    """Mark existing device types as predefined"""
    DeviceType = apps.get_model('devices', 'DeviceType')

    # List of predefined device type slugs
    predefined_slugs = [
        'router',
        'switch',
        'firewall',
        'server',
        'access-point',
    ]

    # Mark existing types as predefined
    DeviceType.objects.filter(slug__in=predefined_slugs).update(is_predefined=True)
    print(f"Marked {DeviceType.objects.filter(is_predefined=True).count()} device types as predefined")


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_populate_vendor_backup_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='is_predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_predefined_device_types, migrations.RunPython.noop),
    ]
