# Generated by Django 5.2.8 on 2025-11-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('configuration_encrypted', models.TextField()),
                ('configuration_hash', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('output_log', models.TextField(blank=True)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('has_changes', models.BooleanField(default=True)),
                ('changes_summary', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='devices.device')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_content', models.TextField()),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('modifications', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_new', to='backups.backup')),
                ('backup_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_as_old', to='backups.backup')),
            ],
            options={
                'verbose_name': 'Backup Diff',
                'verbose_name_plural': 'Backup Diffs',
                'db_table': 'backup_diffs',
            },
        ),
        migrations.CreateModel(
            name='BackupRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keep_last_n', models.IntegerField(default=10, help_text='Keep last N backups')),
                ('keep_daily', models.IntegerField(default=7, help_text='Keep daily backups for N days')),
                ('keep_weekly', models.IntegerField(default=4, help_text='Keep weekly backups for N weeks')),
                ('keep_monthly', models.IntegerField(default=12, help_text='Keep monthly backups for N months')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_delete', models.BooleanField(default=False, help_text='Automatically delete old backups')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='retention_policies', to='devices.device')),
            ],
            options={
                'verbose_name': 'Backup Retention Policy',
                'verbose_name_plural': 'Backup Retention Policies',
                'db_table': 'backup_retention_policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schedule_expression', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('successful_runs', models.IntegerField(default=0)),
                ('failed_runs', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_schedules_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='devices.device')),
            ],
            options={
                'verbose_name': 'Backup Schedule',
                'verbose_name_plural': 'Backup Schedules',
                'db_table': 'backup_schedules',
                'ordering': ['device', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['device', '-created_at'], name='backups_device__f114a4_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['status'], name='backups_status_c02d44_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['-created_at'], name='backups_created_bfe26c_idx'),
        ),
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['configuration_hash'], name='backups_configu_2dfb67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backupdiff',
            unique_together={('backup_new', 'backup_old')},
        ),
    ]
