# Generated by Django 5.2.8 on 2025-11-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupschedule',
            options={'ordering': ['name'], 'verbose_name': 'Backup Schedule', 'verbose_name_plural': 'Backup Schedules'},
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='device',
        ),
        migrations.RemoveField(
            model_name='backupschedule',
            name='schedule_expression',
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='device_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='devices.devicegroup'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='backup_schedules', to='devices.device'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='run_days',
            field=models.CharField(blank=True, help_text='Days of week (0=Mon, 6=Sun), comma-separated', max_length=50),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='run_time',
            field=models.TimeField(blank=True, help_text='Time to run (for daily/weekly/monthly)', null=True),
        ),
    ]
