# Generated by Django 5.2.8 on 2025-11-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_alter_backupschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='backups.backupschedule'),
        ),
    ]
